name: React Firebase CICD
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: ./dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    env:
      FIREBASE_KEY: ${{ secrets.FIREBASE_KEY }}
      FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
      FIREBASE_CLI_EXPERIMENTS: webframeworks

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Firebase Tools
        run: npm install -g firebase-tools

      - name: Check Firebase CLI version
        run: firebase --version

      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: build
          path: ./dist

      - name: make FIREBASE_KEY
        run: |
          echo "${{ secrets.FIREBASE_KEY }}" | base64 -d > ./firebase-key.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=${{ github.workspace }}/firebase-key.json" >> $GITHUB_ENV

      - name: Validate Firebase Key
        run: cat ./firebase-key.json

      - name: Check dist directory contents
        run: ls -la ./dist

      - name: Check firebase.json exists
        run: ls -la

      - name: Check GOOGLE_APPLICATION_CREDENTIALS
        run: echo $GOOGLE_APPLICATION_CREDENTIALS

      # - name: Deploy Firebase hosting
      #   shell: bash
      #   run: firebase deploy --only hosting

      - name: Deploy Firebase hosting with debug
        shell: bash
        run: firebase deploy --only hosting --debug

      - name: Remove Credentials File
        if: success() || failure()
        run: rm firebase-key.json
